### ISSUE TITLE
Замечания по программе Adapter

### ISSUE THREAD

**Issue by oMystique** [panic-torra/ood#4]
- [x] Сделать CRGBAColor структурой.
- [x] Альфа-компонент структуры CRGBAColor сделать по дефолту равным 1, а не проставлять каждый раз руками значение
- [x] Избавиться от инициализации цвета по типу m_rgbaColor(0, 0, 0, 0) и с остальными структурами так же.
- [x] Покрыть CModernGraphicsRenderer тестами, где будет выбрасываться исключение
- [x] Покрыть тестами деструктор CModernGraphicsRenderer

**Comment by alexey-malov** [comment]
- [ ] Дефолтные параметры одного конструктора плохо подходят. Сделать default-конструктор, конструктор с 3 параметрами, и со всеми четырьмя

**Comment by alexey-malov** [comment]
- [ ] Нельзя явно вызывать деструктор объекта с автоматическим временем жизни
